# site web Ciel

# Utilise la dernière version de l'image httpd (serveur web Apache) comme image de base.
FROM httpd:latest
# Copie le fichier 'index.html' de ton répertoire local vers le répertoire des documents racine
# du serveur Apache à l'intérieur du conteneur.
COPY index.html /usr/local/apache2/htdocs/
