# Exemple Docker-copmpse Blog wordpress

version: "3.9"                                       # Version de Docker Compose à utiliser

services:
  db:                                                # Nom du premier service, ici une base de données
    image: mysql:5.7                                 # Image Docker utilisée pour ce service, ici mysql:5.7  
    volumes:
      - db_data:/var/lib/mysql                       # Lie le volume nommé 'db_data' au répertoire de données MySQL dans le conteneur
    restart: always                                  # Redémarre automatiquement le conteneur en cas d'erreur
    environment:
      MYSQL_ROOT_PASSWORD: motdepassehabituellab     # Définit le mot de passe de l'utilisateur root de MySQL, mettre notre mot de passe pour le lab.
      MYSQL_DATABASE: wordpress                      # Crée une base de données nommée 'wordpress'
      MYSQL_USER: wordpressuser                      # Crée un utilisateur MySQL nommé 'wordpressuser'
      MYSQL_PASSWORD: motdepassehabituellab          # Définit le mot de passe de l'utilisateur , mettre notre mot de passe pour le lab.

  wordpress:                                         # Nom du deuxième service : l'application WordPress
    depends_on:                                      # Les dépendences
      - db                                           # S'assure que le service 'db' est démarré avant 'wordpress'
    image: wordpress:latest   
    ports:
      - "8000:80"                                    # Expose le port 80 du conteneur sur le port 8000 de l'hôte
    restart: always                                  # Redémarre automatiquement le conteneur en cas d'erreur
    environment:
      WORDPRESS_DB_HOST: db:3306                     # Indique à WordPress l'adresse et le port de la base de données MySQL (nom du service 'db' résolu par Docker)
      WORDPRESS_DB_USER: wordpressuser               # Nom d'utilisateur pour se connecter à la base de données WordPress
      WORDPRESS_DB_PASSWORD: motdepassehabituellab   # Mot de passe pour se connecter à la base de données WordPress , mettre notre mot de passe pour le lab.
      WORDPRESS_DB_NAME: wordpress                   # Nom de la base de données que WordPress doit utiliser
volumes:
  db_data: {}                                        # Déclaration du volume nommé 'db_data' pour la persistance des données MySQL
