# Exemple Docker-copmpse pour portainer

version: '3'                                               # Version de Docker Compose à utiliser
services:
  portainer:                                               # Nom du premier service, ici portainers
    image: portainer/portainer-ce                          # Image Docker utilisée pour ce service, ici portainer-ce 
    ports:
      - 9000:9000                                          # Expose le port 9000 du conteneur sur le port 9000 de l'hôte
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock          # Monte le socket Docker de l'hôte dans le conteneur pour permettre à Portainer de gérer Docker
      - portainer_data:/data                               # Crée un volume nommé 'portainer_data' et le monte dans le conteneur pour stocker les données de Portainer
    restart: always                                        # Redémarre automatiquement le conteneur en cas d'erreur
volumes:
  portainer_data:                                          # Définition du volume nommé portainer_data pour la persistance des données de Portainer
